import os

path = "/home/kaue/opensidewalkmap_beta/oswm_codebase/data_quality/completeness/completeness_lib.py"

with open(path, "r", encoding="utf-8") as f:
    content = f.read()

# Update generate_completeness_map call to pass attribute_rules_js
old_gen_call = '''    html = _build_map_html(
        geojson_str=json.dumps(geojson),
        boundary_geojson_str=boundary_geojson_str,
        center_lon=center_lon,
        center_lat=center_lat,
        city_name=city_name,
        timestamps_js=timestamp_labels_js,
        n_timestamps=len(timestamps),
    )'''

new_gen_call = '''    html = _build_map_html(
        geojson_str=json.dumps(geojson),
        boundary_geojson_str=boundary_geojson_str,
        center_lon=center_lon,
        center_lat=center_lat,
        city_name=city_name,
        timestamps_js=timestamp_labels_js,
        n_timestamps=len(timestamps),
        attribute_rules_js=json.dumps(ATTRIBUTE_RULES),
    )'''

if old_gen_call in content:
    content = content.replace(old_gen_call, new_gen_call)

start_idx = content.find("def _build_map_html(")
if start_idx == -1:
    print("Could not find _build_map_html")
    exit(1)

new_content = content[:start_idx]

new_func = '''def _build_map_html(geojson_str, boundary_geojson_str, center_lon, center_lat, city_name, timestamps_js, n_timestamps, attribute_rules_js):
    """Build the standalone MapLibre GL HTML string."""

    last_idx = n_timestamps - 1
    favicon_url = branding_asset_url("favicon", "../../oswm_codebase")
    project_logo_url = branding_asset_url("logos.project", "../../oswm_codebase")

    return f"""<!--
  Generated automatically by oswm_codebase/data_quality/completeness/completeness_lib.py
  Do not edit this file directly.
-->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OSWM Completeness Analysis — {city_name}</title>
<link rel="icon" type="image/x-icon" href="{favicon_url}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<script src="https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.js"></script>
<link href="https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.css" rel="stylesheet">
<script src="https://unpkg.com/pmtiles@3.0.6/dist/pmtiles.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://unpkg.com/@sgratzl/chartjs-chart-boxplot@4.3.1/build/index.umd.min.js"></script>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Outfit', sans-serif; background: #0f172a; color: #f8fafc; }}
  #map {{ position: absolute; top: 0; left: 0; width: 100%; height: 100%; }}

  .top-bar {{
    position: absolute; top: 0; left: 0; width: 100%; z-index: 20;
    background: rgba(15, 23, 42, 0.88); backdrop-filter: blur(12px);
    border-bottom: 1px solid rgba(255,255,255,0.1);
    padding: 10px 20px; display: flex; align-items: center; justify-content: space-between;
    box-shadow: 0 4px 15px rgba(0,0,0,0.2);
  }}
  .top-bar .header-left {{
    display: flex; align-items: center; gap: 16px;
  }}
  .top-bar a.back-btn {{
    background: rgba(255,255,255,0.05); border: 1px solid rgba(0,242,254,0.3);
    color: #00f2fe; padding: 6px 12px; border-radius: 6px; text-decoration: none;
    font-size: 0.9rem; font-weight: 500; transition: 0.2s;
  }}
  .top-bar a.back-btn:hover {{
    background: rgba(0,242,254,0.15);
  }}
  .top-bar h3 {{
    color: #f8fafc; font-size: 1.15rem; font-weight: 600; letter-spacing: 0.5px;
    text-shadow: 0 2px 4px rgba(0,0,0,0.3); display: flex; align-items: center;
  }}
  .top-bar h3 img {{ height: 1.5em; vertical-align: middle; margin-right: 10px; }}

  .mode-switch {{
    display: flex; background: rgba(15, 23, 42, 0.92); border: 1px solid rgba(255,255,255,0.15);
    border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.2);
  }}
  .mode-switch button {{
    padding: 6px 16px; font-family: 'Outfit', sans-serif; font-size: 0.85rem; font-weight: 500;
    cursor: pointer; transition: all 0.2s ease; border: none; outline: none;
    background: transparent; color: #cbd5e1;
  }}
  .mode-switch button.active {{
    background: rgba(0, 242, 254, 0.15); color: #00f2fe; font-weight: 600;
  }}
  .mode-switch button:hover:not(.active) {{
    color: #f8fafc; background: rgba(255, 255, 255, 0.05);
  }}

  .controls {{
    position: absolute; top: 64px; right: 12px; z-index: 10;
    background: rgba(15, 23, 42, 0.92); backdrop-filter: blur(14px);
    border: 1px solid rgba(255,255,255,0.1); border-radius: 10px;
    padding: 14px 16px; min-width: 220px;
    box-shadow: 0 8px 24px rgba(0,0,0,0.25);
  }}
  .controls h4 {{ color: #00f2fe; font-size: 0.85rem; margin-bottom: 10px; font-weight: 600; }}
  .controls label {{
    display: flex; align-items: center; gap: 8px; cursor: pointer;
    padding: 4px 0; font-size: 0.85rem; color: #cbd5e1;
  }}
  .controls label:hover {{ color: #f8fafc; }}
  .controls input[type="radio"], .controls input[type="checkbox"] {{ accent-color: #00f2fe; }}
  .controls .divider {{
    border-top: 1px solid rgba(255,255,255,0.08); margin: 10px 0;
  }}
  .controls .slider-group {{ margin-top: 6px; }}
  .controls .slider-group .label-row {{
    display: flex; justify-content: space-between; align-items: center;
    font-size: 0.8rem; color: #94a3b8; margin-bottom: 4px;
  }}
  .controls input[type="range"] {{
    width: 100%; accent-color: #00f2fe; cursor: pointer;
  }}

  .legend {{
    position: absolute; bottom: 30px; left: 12px; z-index: 10;
    background: rgba(15, 23, 42, 0.92); backdrop-filter: blur(14px);
    border: 1px solid rgba(255,255,255,0.1); border-radius: 10px;
    padding: 12px 16px; box-shadow: 0 8px 24px rgba(0,0,0,0.25);
  }}
  .legend h4 {{ color: #00f2fe; font-size: 0.8rem; margin-bottom: 8px; font-weight: 600; }}
  .legend .bar {{
    width: 180px; height: 14px; border-radius: 4px;
    background: linear-gradient(to right, #d73027, #fc8d59, #fee08b, #d9ef8b, #66bd63, #1a9850);
  }}
  .legend .labels {{
    display: flex; justify-content: space-between; font-size: 0.7rem;
    color: #94a3b8; margin-top: 3px;
  }}
  .legend .no-data {{
    display: flex; align-items: center; gap: 6px; margin-top: 6px;
    font-size: 0.7rem; color: #94a3b8;
  }}
  .legend .no-data .swatch {{
    width: 14px; height: 14px; border-radius: 3px; background: #475569;
  }}
</style>
</head>
<body>

<div id="map"></div>

<div class="top-bar">
  <div class="header-left">
    <a class="back-btn" href="../oswm_qc_main.html">← Back to QC Main</a>
    <h3>
      <img src="{project_logo_url}" alt="OSWM">
      Pedestrian Network Completeness — {city_name}
    </h3>
  </div>
  <div class="mode-switch">
    <button id="mode-geometry" class="active">Geometry</button>
    <button id="mode-attributes">Attributes</button>
  </div>
</div>

<div class="controls">
  <div id="controls-geometry">
    <h4>Geometry Layer</h4>
    <label><input type="radio" name="metric_geom" value="footway" checked> Footway / Road</label>
    <label><input type="radio" name="metric_geom" value="sidewalk"> Sidewalk / Road</label>
  </div>
  <div id="controls-attributes" style="display:none;">
    <h4>Attribute Tag</h4>
    <label><input type="radio" name="metric_attr" value="surface" checked> Surface</label>
    <label><input type="radio" name="metric_attr" value="smoothness"> Smoothness</label>
    <label><input type="radio" name="metric_attr" value="width"> Width</label>
    <label><input type="radio" name="metric_attr" value="tactile_paving"> Tactile Paving</label>
    <label><input type="radio" name="metric_attr" value="wheelchair"> Wheelchair</label>
    <label><input type="radio" name="metric_attr" value="kerb"> Kerb</label>
    
    <div class="divider"></div>
    <label style="color:#00f2fe; font-weight:600;"><input type="checkbox" id="show-features-cb"> Show Features</label>
  </div>
  <div class="divider" id="time-divider" style="display:{{'block' if n_timestamps > 1 else 'none'}}"></div>
  <div class="slider-group" id="time-slider-group" style="display:{{'block' if n_timestamps > 1 else 'none'}}">
    <div class="label-row">
      <span>Timestamp</span>
      <span id="ts-label"></span>
    </div>
    <input type="range" id="ts-slider" min="0" max="{last_idx}" value="{last_idx}" step="1">
  </div>
</div>

<button id="stats-btn" style="position: absolute; bottom: 240px; left: 12px; z-index: 10; width: 44px; height: 44px; border-radius: 50%; background: rgba(15, 23, 42, 0.92); border: 1px solid rgba(255,255,255,0.1); box-shadow: 0 4px 12px rgba(0,0,0,0.3); color: #00f2fe; cursor: pointer; display: flex; align-items: center; justify-content: center; backdrop-filter: blur(14px);">
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
</button>

<div id="stats-modal" style="display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.6); z-index:9999; backdrop-filter:blur(4px); align-items:center; justify-content:center;">
  <div style="background:rgba(15, 23, 42, 0.95); border:1px solid rgba(0, 242, 254, 0.3); border-radius:12px; box-shadow:0 12px 32px rgba(0,0,0,0.5); padding:20px; width:800px; max-width:95vw;">
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:16px; border-bottom:1px solid rgba(255,255,255,0.1); padding-bottom:12px;">
      <h3 style="color:#00f2fe; margin:0; font-size:1.2rem;">Tile Statistics</h3>
      <button id="close-stats" style="background:none; border:none; color:#94a3b8; font-size:24px; cursor:pointer; line-height:1;">&times;</button>
    </div>
    <div style="display:flex; gap:20px; flex-wrap:wrap;">
      <div style="flex:1; min-width:300px; height:300px; position:relative;">
        <canvas id="hist-canvas"></canvas>
      </div>
      <div style="flex:1; min-width:300px; height:300px; position:relative;">
        <canvas id="box-canvas"></canvas>
      </div>
    </div>
  </div>
</div>

<div class="legend">
  <h4 id="legend-title">Footway / Road Ratio</h4>
  <div class="bar"></div>
  <div class="labels"><span>0</span><span>0.25</span><span>0.5</span><span>0.75</span><span>1.0+</span></div>
  <div class="no-data"><div class="swatch"></div><span>No road data</span></div>

  <div style="border-top: 1px solid rgba(255,255,255,0.08); margin: 12px 0 8px;"></div>
  <label style="display:flex; align-items:center; gap:8px; font-size:0.8rem; color:#cbd5e1; cursor:pointer;">
    <input type="checkbox" id="auto-scale-cb" checked style="accent-color: #00f2fe;"> Auto-scale zoom
  </label>
  <div id="manual-zoom-group" style="display:none; margin-top:8px;">
    <div style="display:flex; justify-content:space-between; font-size:0.75rem; color:#94a3b8; margin-bottom:4px;">
      <span>Manual Zoom</span>
      <span id="manual-zoom-label">Z12</span>
    </div>
    <input type="range" id="manual-zoom-slider" min="{MIN_ZOOM}" max="{MAX_ZOOM}" value="{MIN_ZOOM}" step="1" style="width:100%; accent-color:#00f2fe; cursor:pointer;">
  </div>
</div>

<script>
let protocol = new pmtiles.Protocol();
maplibregl.addProtocol("pmtiles", protocol.tile);

const TIMESTAMPS = {timestamps_js};
const GEOJSON = {geojson_str};
const BOUNDARY_GEOJSON = {boundary_geojson_str};
const ATTRIBUTE_RULES = {attribute_rules_js};

const map = new maplibregl.Map({{
  container: 'map',
  style: {{
    version: 8,
    sources: {{
      'carto': {{
        type: 'raster',
        tiles: ['https://{{s}}.basemaps.cartocdn.com/dark_all/{{z}}/{{x}}/{{y}}@2x.png'.replace('{{s}}', 'a')],
        tileSize: 256,
        attribution: '&copy; <a href="https://carto.com/">CARTO</a> &copy; <a href="https://www.openstreetmap.org/copyright">OSM</a>'
      }}
    }},
    layers: [{{ id: 'carto-tiles', type: 'raster', source: 'carto' }}]
  }},
  center: [{center_lon}, {center_lat}],
  zoom: 12,
  minZoom: 10,
  maxZoom: 18
}});

map.addControl(new maplibregl.NavigationControl(), 'bottom-right');
map.addControl(new maplibregl.ScaleControl({{ unit: 'metric' }}), 'bottom-right');

let currentMode = 'geometry';
let currentMetricGeom = 'footway';
let currentMetricAttr = 'surface';
let showFeatures = false;
let currentTsIdx = {last_idx};

function ratioToColor(ratio) {{
  if (ratio === null || ratio === undefined) return 'rgba(71, 85, 105, 0.5)';
  const r = Math.min(ratio, 1.0);
  const stops = [
    [0.0, [215, 48, 39]],
    [0.15, [252, 141, 89]],
    [0.3, [254, 224, 139]],
    [0.5, [217, 239, 139]],
    [0.75, [102, 189, 99]],
    [1.0, [26, 152, 80]]
  ];
  let lower = stops[0], upper = stops[stops.length - 1];
  for (let i = 0; i < stops.length - 1; i++) {{
    if (r >= stops[i][0] && r <= stops[i+1][0]) {{
      lower = stops[i]; upper = stops[i+1]; break;
    }}
  }}
  const t = upper[0] === lower[0] ? 1 : (r - lower[0]) / (upper[0] - lower[0]);
  const c = lower[1].map((v, j) => Math.round(v + t * (upper[1][j] - v)));
  return `rgba(${{c[0]}}, ${{c[1]}}, ${{c[2]}}, 0.55)`;
}}

function updateFeatureColors() {{
  const isAttr = (currentMode === 'attributes');
  const suffix = isAttr ? '_t' + {last_idx} : '_t' + currentTsIdx;
  const prop = isAttr ? (currentMetricAttr + '_ratio') : (currentMetricGeom === 'footway' ? 'footway_ratio' : 'sidewalk_ratio');
  const key = prop + suffix;

  GEOJSON.features.forEach(f => {{
    f.properties._color = ratioToColor(f.properties[key]);
  }});

  if (map.getSource('tiles')) {{
    map.getSource('tiles').setData(GEOJSON);
  }}

  const fillOp = (isAttr && showFeatures) ? 0.0 : 0.7;
  for (let z = {MIN_ZOOM}; z <= {MAX_ZOOM}; z++) {{
    const layerId = 'tiles-z' + z;
    if (map.getLayer(layerId)) {{
      map.setPaintProperty(layerId, 'fill-opacity', fillOp);
    }}
  }}

  if (isAttr) {{
    const titles = {{ surface: 'Surface', smoothness: 'Smoothness', width: 'Width', tactile_paving: 'Tactile Paving', wheelchair: 'Wheelchair', kerb: 'Kerb' }};
    document.getElementById('legend-title').textContent = titles[currentMetricAttr] + ' Completeness';
  }} else {{
    document.getElementById('legend-title').textContent = currentMetricGeom === 'footway' ? 'Footway / Road Ratio' : 'Sidewalk / Road Ratio';
  }}
}}

function updateFeatureLayers() {{
  if (!map.loaded()) return;

  const existingLayers = map.getStyle().layers.filter(l => l.id.startsWith('feature-layer-'));
  existingLayers.forEach(l => map.removeLayer(l.id));
  const existingSources = Object.keys(map.getStyle().sources).filter(s => s.startsWith('pmtiles-'));
  existingSources.forEach(s => map.removeSource(s));

  if (currentMode === 'attributes' && showFeatures) {{
    const layersToLoad = ATTRIBUTE_RULES[currentMetricAttr] || [];
    layersToLoad.forEach(lname => {{
      const sourceId = 'pmtiles-' + lname;
      map.addSource(sourceId, {{
        type: 'vector',
        url: 'pmtiles://../../data/tiles/' + lname + '.pmtiles'
      }});
      
      const filterHasTag = ['!=', ['get', currentMetricAttr], null];
      const colorExpr = ['case', filterHasTag, '#1a9850', '#d73027'];

      map.addLayer({{
        id: 'feature-layer-line-' + lname,
        type: 'line',
        source: sourceId,
        'source-layer': lname,
        paint: {{
          'line-color': colorExpr,
          'line-width': 2.5
        }},
        filter: ['==', ['geometry-type'], 'LineString']
      }});

      map.addLayer({{
        id: 'feature-layer-circle-' + lname,
        type: 'circle',
        source: sourceId,
        'source-layer': lname,
        paint: {{
          'circle-color': colorExpr,
          'circle-radius': 3.5,
          'circle-stroke-width': 1,
          'circle-stroke-color': '#0f172a'
        }},
        filter: ['any', ['==', ['geometry-type'], 'Point'], ['==', ['geometry-type'], 'MultiPoint']]
      }});
      
      map.addLayer({{
        id: 'feature-layer-fill-' + lname,
        type: 'fill',
        source: sourceId,
        'source-layer': lname,
        paint: {{
          'fill-color': colorExpr,
          'fill-opacity': 0.5
        }},
        filter: ['any', ['==', ['geometry-type'], 'Polygon'], ['==', ['geometry-type'], 'MultiPolygon']]
      }});
    }});
  }}
}}

function updateTimestampLabel() {{
  document.getElementById('ts-label').textContent = TIMESTAMPS[currentTsIdx] || '';
}}

let autoScale = true;
let manualZoom = {MIN_ZOOM};

function getActiveZoomLevel() {{
  if (autoScale) {{
    let z = Math.round(map.getZoom());
    if (z < {MIN_ZOOM}) z = {MIN_ZOOM};
    if (z > {MAX_ZOOM}) z = {MAX_ZOOM};
    return z;
  }} else {{
    return manualZoom;
  }}
}}

function updateLayerVisibility() {{
  const activeZ = getActiveZoomLevel();
  for (let z = {MIN_ZOOM}; z <= {MAX_ZOOM}; z++) {{
    const layerId = 'tiles-z' + z;
    if (map.getLayer(layerId)) {{
      map.setLayoutProperty(layerId, 'visibility', z === activeZ ? 'visible' : 'none');
    }}
  }}
}}

let histChart = null;
let boxChart = null;

function renderStatsCharts() {{
  if (document.getElementById('stats-modal').style.display === 'none') return;
  const activeZ = getActiveZoomLevel();
  const isAttr = (currentMode === 'attributes');
  const suffix = isAttr ? '_t' + {last_idx} : '_t' + currentTsIdx;
  const prop = isAttr ? (currentMetricAttr + '_ratio') : (currentMetricGeom === 'footway' ? 'footway_ratio' : 'sidewalk_ratio');
  const metricProp = prop + suffix;
  
  const ratios = [];
  GEOJSON.features.forEach(f => {{
    if (f.properties.zoom === activeZ) {{
      const val = f.properties[metricProp];
      if (val !== null && val !== undefined) {{
        ratios.push(val);
      }}
    }}
  }});

  const bins = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
  ratios.forEach(r => {{
    let bin = Math.floor(r * 10);
    if (bin >= 10) bin = 9;
    bins[bin]++;
  }});
  const histLabels = ['0-0.1', '0.1-0.2', '0.2-0.3', '0.3-0.4', '0.4-0.5', '0.5-0.6', '0.6-0.7', '0.7-0.8', '0.8-0.9', '0.9-1.0+'];

  if (histChart) histChart.destroy();
  const histCtx = document.getElementById('hist-canvas').getContext('2d');
  histChart = new Chart(histCtx, {{
    type: 'bar',
    data: {{
      labels: histLabels,
      datasets: [{{
        label: 'Tile Count',
        data: bins,
        backgroundColor: 'rgba(0, 242, 254, 0.4)',
        borderColor: '#00f2fe',
        borderWidth: 1
      }}]
    }},
    options: {{
      responsive: true,
      maintainAspectRatio: false,
      plugins: {{
        legend: {{ display: false }},
        title: {{ display: true, text: 'Ratio Histogram (Z' + activeZ + ')', color: '#f8fafc' }}
      }},
      scales: {{
        y: {{ ticks: {{ color: '#94a3b8' }}, grid: {{ color: 'rgba(255,255,255,0.05)' }} }},
        x: {{ ticks: {{ color: '#94a3b8', font: {{ size: 10 }} }}, grid: {{ display: false }} }}
      }}
    }}
  }});

  if (boxChart) boxChart.destroy();
  const boxCtx = document.getElementById('box-canvas').getContext('2d');
  boxChart = new Chart(boxCtx, {{
    type: 'boxplot',
    data: {{
      labels: ['Ratio Distribution'],
      datasets: [{{
        label: 'Dataset',
        data: [ratios],
        backgroundColor: 'rgba(0, 242, 254, 0.4)',
        borderColor: '#00f2fe',
        borderWidth: 1,
        outlierBackgroundColor: 'rgba(215, 48, 39, 0.8)',
        outlierBorderColor: '#d73027'
      }}]
    }},
    options: {{
      responsive: true,
      maintainAspectRatio: false,
      plugins: {{
        legend: {{ display: false }},
        title: {{ display: true, text: 'Ratio Boxplot (Z' + activeZ + ')', color: '#f8fafc' }}
      }},
      scales: {{
        y: {{ min: 0, max: 1.05, ticks: {{ color: '#94a3b8' }}, grid: {{ color: 'rgba(255,255,255,0.05)' }} }},
        x: {{ ticks: {{ color: '#94a3b8' }}, grid: {{ display: false }} }}
      }}
    }}
  }});
}}

map.on('zoom', () => {{
  if (autoScale) {{
    updateLayerVisibility();
    renderStatsCharts();
  }}
}});

map.on('load', () => {{
  updateFeatureColors();
  updateTimestampLabel();
  updateFeatureLayers();

  map.addSource('tiles', {{ type: 'geojson', data: GEOJSON }});
  map.addSource('boundary', {{ type: 'geojson', data: BOUNDARY_GEOJSON }});

  map.addLayer({{
    id: 'city-boundary-line',
    type: 'line',
    source: 'boundary',
    paint: {{
      'line-color': '#00f2fe',
      'line-width': 2.5,
      'line-dasharray': [2, 2],
      'line-opacity': 0.8
    }}
  }});

  for (let z = {MIN_ZOOM}; z <= {MAX_ZOOM}; z++) {{
    map.addLayer({{
      id: 'tiles-z' + z,
      type: 'fill',
      source: 'tiles',
      filter: ['==', ['get', 'zoom'], z],
      paint: {{
        'fill-color': ['get', '_color'],
        'fill-opacity': 0.7,
        'fill-outline-color': 'rgba(255,255,255,0.25)'
      }}
    }});
  }}

  updateLayerVisibility();

  for (let z = {MIN_ZOOM}; z <= {MAX_ZOOM}; z++) {{
    map.on('click', 'tiles-z' + z, (e) => {{
      const f = e.features[0];
      const p = f.properties;
      const isAttr = (currentMode === 'attributes');
      const suffix = isAttr ? '_t' + {last_idx} : '_t' + currentTsIdx;
      
      const bStr = `${{p.bbox[0]}},${{p.bbox[1]}},${{p.bbox[2]}},${{p.bbox[3]}}`;
      const centerLat = (p.bbox[1] + p.bbox[3]) / 2;
      const centerLon = (p.bbox[0] + p.bbox[2]) / 2;
      
      let osmLinks = `<a href="https://www.openstreetmap.org/#map=${{z}}/${{centerLat}}/${{centerLon}}" target="_blank" style="color:#00f2fe;text-decoration:none;font-size:11px;border:1px solid rgba(0,242,254,0.3);padding:2px 6px;border-radius:4px;margin-right:4px;">View on OSM</a>`;
      if (z >= 16) {{
        osmLinks += `<a href="https://www.openstreetmap.org/edit#map=17/${{centerLat}}/${{centerLon}}" target="_blank" style="color:#00f2fe;text-decoration:none;font-size:11px;border:1px solid rgba(0,242,254,0.3);padding:2px 6px;border-radius:4px;">Edit on OSM</a>`;
      }}

      let html = '';
      if (isAttr) {{
        const tgdRatio = p[currentMetricAttr + '_ratio' + suffix];
        const tgdStr = tgdRatio !== null && tgdRatio !== undefined ? (tgdRatio * 100).toFixed(1) + '%' : 'N/A';
        html = `
          <div style="font-family:Outfit,sans-serif;width:100%;">
            <h4 style="margin:0 0 6px;color:#00f2fe;font-size:13px;border-bottom:1px solid rgba(255,255,255,0.1);padding-bottom:4px;display:flex;justify-content:space-between;align-items:center;">
              Tile ${{p.tile_id}}
              <button onclick="navigator.clipboard.writeText('${{bStr}}')" style="background:none;border:none;color:#94a3b8;cursor:pointer;font-size:11px;text-decoration:underline;">Copy BBox</button>
            </h4>
            <div style="font-size:12px;color:#cbd5e1;line-height:1.6">
              <b>Tag Completeness:</b> ${{tgdStr}}<br>
            </div>
            <div style="margin-top:8px;">${{osmLinks}}</div>
          </div>`;
      }} else {{
        const roadLen = (p['road_length' + suffix] || 0).toFixed(0);
        const footLen = (p['footway_length' + suffix] || 0).toFixed(0);
        const swLen = (p['sidewalk_length' + suffix] || 0).toFixed(0);
        const fRatio = p['footway_ratio' + suffix];
        const sRatio = p['sidewalk_ratio' + suffix];

        html = `
          <div style="font-family:Outfit,sans-serif;width:100%;">
            <h4 style="margin:0 0 6px;color:#00f2fe;font-size:13px;border-bottom:1px solid rgba(255,255,255,0.1);padding-bottom:4px;display:flex;justify-content:space-between;align-items:center;">
              Tile ${{p.tile_id}}
              <button onclick="navigator.clipboard.writeText('${{bStr}}')" style="background:none;border:none;color:#94a3b8;cursor:pointer;font-size:11px;text-decoration:underline;">Copy BBox</button>
            </h4>
            <div style="font-size:12px;color:#cbd5e1;line-height:1.6">
              <b>Roads:</b> ${{Number(roadLen).toLocaleString()}} m<br>
              <b>Footways:</b> ${{Number(footLen).toLocaleString()}} m<br>
              <b>Sidewalks:</b> ${{Number(swLen).toLocaleString()}} m<br>
              <b>Footway ratio:</b> ${{fRatio != null ? (fRatio * 100).toFixed(1) + '%' : 'N/A'}}<br>
              <b>Sidewalk ratio:</b> ${{sRatio != null ? (sRatio * 100).toFixed(1) + '%' : 'N/A'}}
            </div>
            <div style="margin-top:8px;">${{osmLinks}}</div>
            <div style="margin-top:12px; height:120px; width:100%; position:relative;">
              <canvas id="popup-chart"></canvas>
            </div>
          </div>`;
      }}

      const popup = new maplibregl.Popup({{ className: 'dark-popup' }})
        .setLngLat(e.lngLat).setHTML(html).addTo(map);

      if (!isAttr) {{
        const canvas = popup.getElement().querySelector('#popup-chart');
        if (canvas) {{
          const chartData = [];
          for (let i = 0; i < TIMESTAMPS.length; i++) {{
            const r = p[(currentMetricGeom === 'footway' ? 'footway_ratio' : 'sidewalk_ratio') + '_t' + i];
            chartData.push(r !== null && r !== undefined ? (r * 100).toFixed(1) : null);
          }}
          const ctx = canvas.getContext('2d');
          new Chart(ctx, {{
            type: 'line',
            data: {{
              labels: TIMESTAMPS,
              datasets: [{{
                label: currentMetricGeom === 'footway' ? 'Footway Ratio (%)' : 'Sidewalk Ratio (%)',
                data: chartData,
                borderColor: '#00f2fe',
                backgroundColor: 'rgba(0, 242, 254, 0.1)',
                borderWidth: 2,
                pointBackgroundColor: '#0f172a',
                pointBorderColor: '#00f2fe',
                pointRadius: 3,
                fill: true,
                tension: 0.2
              }}]
            }},
            options: {{
              responsive: true,
              maintainAspectRatio: false,
              plugins: {{
                legend: {{ display: false }},
                tooltip: {{
                  backgroundColor: 'rgba(15, 23, 42, 0.9)',
                  titleColor: '#00f2fe',
                  bodyColor: '#f8fafc',
                  borderColor: 'rgba(255,255,255,0.1)',
                  borderWidth: 1
                }}
              }},
              scales: {{
                x: {{
                  ticks: {{ color: '#94a3b8', font: {{ size: 9 }}, maxRotation: 45, minRotation: 45 }},
                  grid: {{ color: 'rgba(255,255,255,0.05)' }}
                }},
                y: {{
                  beginAtZero: true,
                  ticks: {{ color: '#94a3b8', font: {{ size: 9 }} }},
                  grid: {{ color: 'rgba(255,255,255,0.05)' }}
                }}
              }}
            }}
          }});
        }}
      }}
    }});

    map.on('mouseenter', 'tiles-z' + z, () => {{ map.getCanvas().style.cursor = 'pointer'; }});
    map.on('mouseleave', 'tiles-z' + z, () => {{ map.getCanvas().style.cursor = ''; }});
  }}
}});

document.getElementById('mode-geometry').addEventListener('click', () => {{
  currentMode = 'geometry';
  document.getElementById('mode-geometry').classList.add('active');
  document.getElementById('mode-attributes').classList.remove('active');
  
  document.getElementById('controls-geometry').style.display = 'block';
  document.getElementById('controls-attributes').style.display = 'none';
  
  if (TIMESTAMPS.length > 1) {{
    document.getElementById('time-slider-group').style.display = 'block';
    document.getElementById('time-divider').style.display = 'block';
  }}
  
  updateFeatureColors();
  updateFeatureLayers();
  renderStatsCharts();
}});

document.getElementById('mode-attributes').addEventListener('click', () => {{
  currentMode = 'attributes';
  document.getElementById('mode-attributes').classList.add('active');
  document.getElementById('mode-geometry').classList.remove('active');
  
  document.getElementById('controls-geometry').style.display = 'none';
  document.getElementById('controls-attributes').style.display = 'block';
  
  document.getElementById('time-slider-group').style.display = 'none';
  document.getElementById('time-divider').style.display = 'none';
  
  updateFeatureColors();
  updateFeatureLayers();
  renderStatsCharts();
}});

document.getElementById('auto-scale-cb').addEventListener('change', (e) => {{
  autoScale = e.target.checked;
  document.getElementById('manual-zoom-group').style.display = autoScale ? 'none' : 'block';
  updateLayerVisibility();
  renderStatsCharts();
}});

document.getElementById('manual-zoom-slider').addEventListener('input', (e) => {{
  manualZoom = parseInt(e.target.value);
  document.getElementById('manual-zoom-label').textContent = 'Z' + manualZoom;
  updateLayerVisibility();
  renderStatsCharts();
}});

document.querySelectorAll('input[name="metric_geom"]').forEach(radio => {{
  radio.addEventListener('change', (e) => {{
    currentMetricGeom = e.target.value;
    updateFeatureColors();
    renderStatsCharts();
  }});
}});

document.querySelectorAll('input[name="metric_attr"]').forEach(radio => {{
  radio.addEventListener('change', (e) => {{
    currentMetricAttr = e.target.value;
    updateFeatureColors();
    updateFeatureLayers();
    renderStatsCharts();
  }});
}});

document.getElementById('show-features-cb').addEventListener('change', (e) => {{
  showFeatures = e.target.checked;
  updateFeatureColors();
  updateFeatureLayers();
}});

document.getElementById('ts-slider').addEventListener('input', (e) => {{
  currentTsIdx = parseInt(e.target.value);
  updateTimestampLabel();
  updateFeatureColors();
  renderStatsCharts();
}});

document.getElementById('stats-btn').addEventListener('click', () => {{
  document.getElementById('stats-modal').style.display = 'flex';
  renderStatsCharts();
}});

document.getElementById('close-stats').addEventListener('click', () => {{
  document.getElementById('stats-modal').style.display = 'none';
}});
</script>

<style>
  .maplibregl-popup-content {{
    background: rgba(15, 23, 42, 0.95) !important;
    border: 1px solid rgba(0, 242, 254, 0.3) !important;
    border-radius: 8px !important;
    box-shadow: 0 8px 24px rgba(0,0,0,0.3) !important;
    padding: 12px !important;
    width: 270px !important;
    max-width: none !important;
  }}
  .maplibregl-popup-tip {{ border-top-color: rgba(15, 23, 42, 0.95) !important; }}
  .maplibregl-popup-close-button {{ color: #94a3b8 !important; font-size: 18px !important; }}
</style>
</body>
</html>
"""
'''

new_content += new_func + "\n"

with open(path, "w", encoding="utf-8") as f:
    f.write(new_content)
print("Updated completeness_lib.py successfully.")
