name: tests

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'
      - run: pip install pytest
      - run: python -m pytest -q
